language: go
services:
  - docker

env:
  COMPOSE_VERSION: 1.28.4

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

install:
  - echo "Ignoring travis install"

jobs:
  include:
    - stage: build docker image
      script:
        - docker-compose build
    - stage: test
      script: 
        - docker-compose run test
    - stage: deploy
      if: branch = main
      script: 
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker-compose build 
        - docker tag gotest:latest mfroes/gotest:v0.0.1
        - docker push mfroes/gotest:v0.0.1
