---
version: "3.8"
services:
  build: &build
    build:
      context: .
      target: build 
    ports:
      - "8090:8090"
    environment:
      GO111MODULE: auto
    entrypoint:
      - go
      - build
    command: 
      - "./..."

  test: 
    <<: *build
    entrypoint:
      - go
      - test
    command: "./..."

  server:
    <<: *build
    image: gotest:latest
    build:
      context: .
      target: dist
    ports:
      - 8090:8090
    entrypoint:
      - /server