---
version: "3.8"
services:
  build: &build
    build:
      context: .
      target: build 
    ports:
      - "8090:8090"
    environment:
      GO111MODULE: auto
    entrypoint:
      - go
      - build

  shell: 
    <<: *build
    entrypoint:
      - bash
    volumes:
      - ".:/build/src/"

  test: 
    image: golang:1.16.0
    entrypoint:
      - go
      - test
    working_dir: /build/src/
    volumes:
      - ".:/build/src/"
    command: "./..."

  server:
    <<: *build
    image: gotest:latest
    build:
      context: .
      target: dist
    ports:
      - 8090:8090
    entrypoint:
      - /server
