---
version: "3.8"
services:
  test:
    build:
      context: .
      target: build 
    ports:
      - "8090:8090"
    environment:
      GO111MODULE: auto
    entrypoint:
      - go
      - test
    command: "./..."

  server:
    image: gotest:latest
    build:
      context: .
    ports:
      - 8090:8090
